### ISSUE TITLE
New filters in jq 1.7

### ISSUE THREAD

**Issue by kklingenberg** [01mf02/jaq#112]
These are:

- [ ] `pick/1` which I believe must be implemented natively, since it involves preserving path information.
- [ ] `abs/0` which is apparently trivial, though from the release notes I guess it'd also need to be native since it should preserve `Val::Num` variants. Maybe it's as simple as preserving the variant [here](https://github.com/01mf02/jaq/blob/c776647e66e3c481a505bd34e333678acb0141d8/jaq-interpret/src/val.rs#L431)?

Source: <https://github.com/jqlang/jq/releases/tag/jq-1.7>

**Comment by 01mf02** [comment]
Unfortunately, I currently do not see a proper way to support `pick/1`, because jaq's update mechanism does not work with paths.
`abs/0`, on the other hand, is trivial to integrate. I'll do that once #202 has landed. :)

**Comment by 01mf02** [comment]
I implemented `abs` in 674547602a24416760e33a16a8fecbdbb6152fba.

**Comment by kklingenberg** [comment]
Thank you @01mf02 ! I originally thought that `abs` (or `-`) needed to preserve the argument's precision ([here](https://github.com/01mf02/jaq/blob/674547602a24416760e33a16a8fecbdbb6152fba/jaq-json/src/lib.rs#L781)). However jq's implementation doesn't, so I guess that's not the case.

```bash
jq -n '-10000000000000001 | abs'
# 1e+16
```
