### ISSUE TITLE
Using jaq-core as a library

### ISSUE THREAD

**Issue by tjbell** [01mf02/jaq#12]
I was wondering if it would be possible to use `jaq-core` or `jaq-std` as a library. I have tried but I get an unresolved import for `jaq_core::Ctx`. Thanks.

**Comment by martinohmann** [comment]
@01mf02  I'd also love to use `jaq` as a library in one of my own projects as well for jq-like filters and transformations. I tried integrating [`jq-rs`](https://github.com/onelson/jq-rs) but it's magnitudes slower than just shelling out to `jq` (which I do atm).

**Comment by martinohmann** [comment]
Thanks, will give that a try!

**Comment by 01mf02** [comment]
@tjbell, perhaps you were not able to import `jaq_core::Ctx` because this was only available in the development version, not in the version on crates.io. I just released a new version of jaq / jaq_core, so perhaps this solves your issue. :)
