### ISSUE TITLE
README markdown syntax error with `<details>`

### ISSUE THREAD

**Issue by lilyball** [01mf02/jaq#135]
In your README, you use `<details>` in a few places, and the contents of the expando are not parsed for markdown syntax. This can make those contents hard to read. This is because Markdown stops parsing when it encounters a block HTML tag, as it assumes you've just pasted some raw HTML in there.

You can work around this by adding blank lines inside of the tag. By moving the contents of the tag to a separate paragraph, Markdown resumes parsing.

This would look like

```md
<details>

Contents go *here*.

</details>
```

Example:

<details>

Contents go *here*.

</details>

or

```md
<details><summary>Example:</summary>

Contents go *here*.

</details>
```

<details><summary>Example:</summary>

Contents go *here*.

</details>

**Comment by 01mf02** [comment]
Thanks for pointing this out! It is indeed much easier to read now. :)
