### ISSUE TITLE
Add option `--exit-status`

### ISSUE THREAD

**Issue by koba-e964** [01mf02/jaq#14]
jq has the option `--exit-status` which reflects the result of filtering to the exit code.

Excerpt from [jq manual](https://github.com/stedolan/jq/blob/master/docs/content/manual/manual.yml):
```
      * `-e` / `--exit-status`:
        Sets the exit status of jq to 0 if the last output values was
        neither `false` nor `null`, 1 if the last output value was
        either `false` or `null`, or 4 if no valid result was ever
        produced.  Normally jq exits with 2 if there was any usage
        problem or system error, 3 if there was a jq program compile
        error, or 0 if the jq program ran.
        Another way to set the exit status is with the `halt_error`
        builtin function.
```

**Comment by 01mf02** [comment]
Hi @koba-e964, this functionality already existed in jaq before; however, so far it was only accessible via `-e`, but not via `--exit-status`. I have now made this change in bfb2a22, where I also added long versions of other jaq options.
Thanks for spotting this!

**Comment by koba-e964** [comment]
Thank you!
