### ISSUE TITLE
Nesting index where parent is not found returns `Error: cannot use null as iterable (array or object)`

### ISSUE THREAD

**Issue by mohan-tenovos** [01mf02/jaq#160]
Where the index is two levels deep and the parent is not found jaq returns `cannot use null as iterable (array or object)`, this behavior is different to jq.

e.g. 

`echo '{ "name": "John" }' | jaq -n '{ "firstName": "John", "lastName": .foo.bar }'`
or
`echo '{ "name": "John" }' | jaq -n '{ "firstName": "John", "lastName": .foo?.bar }'`

I assume I'm missing something obvious....

**Comment by wader** [comment]
Hi, not sure if related to the error but you probably don't want `-n` in this case? (ignore input and use `null` instead).

My guess is this boils down to that jq allows indexing of `null` which returns `null`, ex:
```sh
$ jq -n '.a, .[1], .a.b.c.d, .a[1].b'
null
null
null
null
```

Don't know if it's intentional that jaq throw error instead.

**Comment by 01mf02** [comment]
I would also go with @wader's approach. To prevent future confusion, I added a little note in a83e980e7f011a82a162b07433587e45ae5c376c.
