### ISSUE TITLE
Using JAQ with a custom type

### ISSUE THREAD

**Issue by tusharmath** [01mf02/jaq#173]
Thanks for an amazing library in Rust! I plan to add support for JAQ in https://github.com/tailcallhq/tailcall/issues/1321 However there are a few concerns:

I have a "json-like" structure (not serde_json) that I'd like to integrate with JAQ. Is there a way to do it? What components can I reuse vs re-implement?

**Comment by wader** [comment]
The gojq fork used by [fq](https://github.com/wader/fq) adds a `JQValue` interface to make it possible for any type to behave like a jq value, see https://github.com/wader/gojq/blob/fq/gojq.go#L17 (note that some gojq implementations details leaks into the interface). Maybe can be a useful reference how it could work. It would be very interesting to see other jq implementations allowing things like this but it's understandable if it's out of scope for jaq.

**Comment by 01mf02** [comment]
Hi @tusharmath! I have already thought about making the jaq value type more flexible, in order to support use cases like yours. I suppose that an approach like @wader's could work, and this might even allow jaq to be made flexible enough to support more input formats, like `fq`.

We could, for example, make a `Value` trait that implements just enough functionality such that the jq operations with dedicated syntax (constant value construction, indexing, iteration, arithmetic operations, and the likes) work on it. I believe that that's roughly what @wader did. This would not allow the `core` library to work yet, because it makes more assumptions about the value type (such as having a `length`), but it would be a start.

Can you show us what your value type looks like? That would help fleshing out whether the approach I outlined above would be applicable here.

**Comment by 01mf02** [comment]
(Thanks, @wader, by the way for explaining how you do it in `fq`.)

**Comment by 01mf02** [comment]
@tusharmath, I created a trait in jaq called [`ValT`](https://github.com/01mf02/jaq/blob/1699a7d1fc7ede6f728fcaa243f011137fcc220a/jaq-interpret/src/val.rs#L62) that will eventually allow you to use jaq with any kind of data type that implements this trait. However, so far I did not make this trait public, for I will not be able to make breaking changes to it once I release the next version (at least until jaq 2.0). Can you tell me whether your type could implement this trait?

**Comment by tusharmath** [comment]
Thanks for getting back @01mf02 !

Yes we can implement ValT. I would recommend making the trait public but marking it as unstable and hide it using the unstable feature flag. Folks like us could try it out and give you feedback without expecting a major version increase on breaking changes.

```rust
// This trait will be public if 'unstable' feature is enabled, otherwise it's crate-private
#[cfg_attr(feature = "unstable", pub)]
trait ValT {
    
}

// Implement the trait conditionally
#[cfg(feature = "unstable")]
impl ValT for MyStruct {
   
}
```

**Comment by wader** [comment]
@ssddOnTop hey! just to expand a bit on on my comment above. To implement some fq features (query then hexdump, binary concat/slice etc) it's important that an instance of something that implements the `JQValue` interface should "survive" untouched thru an jq expression evaluation. Not sure if jaq aim's to support something like that and if so that would require use of `dyn` or something? (i'm a rust noob, working on it!)

**Comment by ssddOnTop** [comment]
@wader You are correct. As mentioned [here](https://github.com/01mf02/jaq/issues/173#issuecomment-2075359203) implementation of `ValT` can perform all that operations. My PR just adds (de)serializer to Val, it can only be used for type conversions.

I think I should not like the PR with this issue

**Comment by wader** [comment]
Aha i see 👍

**Comment by 01mf02** [comment]
@tusharmath, I'm happy to hear that you can implement `ValT`. I plan to release a new stable jaq version this week, and I plan to make the `ValT` trait public. Given that I plan to make a breaking release (2.0) next, this can integrate potential necessary changes to `ValT`.

**Comment by 01mf02** [comment]
@wader, the "survival" of jq values is preserved by the introduction of the `ValT` trait, as it happens independently from `ValT`. For example, see the [implementation of `.` (identity filter) in jaq](https://github.com/01mf02/jaq/blob/c78169c7a8a344b3a4d9245e60d5b40f41219422/jaq-interpret/src/filter.rs#L246): This returns the input value unchanged, so the original value "survives". This particular filter can be implemented without `ValT`.
Other operations, like e.g. addition that are handled inside of `ValT`, also always take values "by value" (as opposed to "by reference") and can thus return their original input values; that allows jaq to return the original value when adding `null` to it.

**Comment by wader** [comment]
> @wader, the "survival" of jq values is preserved by the introduction of the `ValT` trait, as it happens independently from `ValT`. For example, see the [implementation of `.` (identity filter) in jaq](https://github.com/01mf02/jaq/blob/c78169c7a8a344b3a4d9245e60d5b40f41219422/jaq-interpret/src/filter.rs#L246): This returns the input value unchanged, so the original value "survives". This particular filter can be implemented without `ValT`. Other operations, like e.g. addition that are handled inside of `ValT`, also always take values "by value" (as opposed to "by reference") and can thus return their original input values; that allows jaq to return the original value when adding `null` to it.

Great! that seem to be more than what my fork does atm. I think that will enable some interesting possibilities. The thing that was trickest and broke to most things when adding a `JQValue` interface to gojq for me has been standard library functions that are implemented with helpers in go for performance, ex things like `to_entries`, `from_entries`, `split`, `join` and `sort`, so mostly functions that work with array of values.

**Comment by 01mf02** [comment]
> Great! that seem to be more than what my fork does atm. I think that will enable some interesting possibilities. The thing that was trickest and broke to most things when adding a `JQValue` interface to gojq for me has been standard library functions that are implemented with helpers in go for performance, ex things like `to_entries`, `from_entries`, `split`, `join` and `sort`, so mostly functions that work with array of values.

Just to clarify, the interface I defined for values is quite minimal right now and only supports operations for which there exists dedicated syntax in jq (such as `.[]` or `f + g`). This excludes any filters that have a name, such as those that you mentioned, i.e. `to_entries`, ..., `sort`. However, I think that most filters that work with strings should be implementable with this interface already. For other filters, this interface is not be expressive enough. When I'll work on making the core library (which provides filters like `length`, `from_entries` etc.) generic over the value types, I'll probably define a new extended interface, or I'll augment the existing interface. I'm still not quite sure about which route to take. :)
