### ISSUE TITLE
Cannot slurp file arguments

### ISSUE THREAD

**Issue by itchyny** [01mf02/jaq#18]
With `--slurp` option, jq reads all the files and collects to an array. Currently `jaq` processes each files individually.
```
 $ jq --slurp . <(echo null) <(echo false) <(echo true)
[
  null,
  false,
  true
]
 $ jaq --slurp . <(echo null) <(echo false) <(echo true)
[
  null
]
[
  false
]
[
  true
]
```

**Comment by 01mf02** [comment]
Yet another good catch. :)
This behaviour is not by accident; slurping this way is significantly easier to implement, in particular when also supporting in-place editing.
And luckily, you can always simulate `jq -s . a b` with `jaq -s . <(cat a b)`.

Still, I agree that this behaviour might be surprising. I have tried to address that by expanding the documentation of `--slurp` in f54edbe.
