### ISSUE TITLE
`halt` and `halt_error` filters

### ISSUE THREAD

**Issue by thecaralice** [01mf02/jaq#195]
Original `jq` has these since [1.6](https://jqlang.github.io/jq/manual/v1.6/#halt_error).
`halt/0` terminates the program with exit code 0, `halt_error/0` terminates the program with exit code 5, `halt_error/1` uses the provided exit code.

**Comment by 01mf02** [comment]
Thanks for catching this. This is probably impossible to support in jaq 1.x due to restrictions in the current API, but with jaq 2.0, this can work. The idea to make it happen is to attach some kind of `bool` to the new `Exn` (exception) type that registers whether the error can be caught or not.

**Comment by 01mf02** [comment]
This is now done in 0278cc0. The implementation was actually much simpler than I thought and did not need any change to the exception type.
