### ISSUE TITLE
GH release naming convention - Remove version from asset name

### ISSUE THREAD

**Issue by polarathene** [01mf02/jaq#211]
As you're approaching a new breaking change release with the `2.0` release, now is a good time to consider improving how the assets are named? (_[more details](https://github.com/caddyserver/xcaddy/issues/192#issuecomment-2350747373)_)

Presently if I download the asset it's like this:

```console
$ wget -q https://github.com/01mf02/jaq/releases/download/v2.0.0-alpha.1/jaq-v2.0.0-alpha.1-x86_64-unknown-linux-musl

$ ls -l jaq*
-rw-r--r-- 1 root root 1412456 Sep  2 14:21 jaq-v2.0.0-alpha.1-x86_64-unknown-linux-musl
```

- I usually see `tar.gz` archives (_or `.zip` for windows_) which allows preserving file attributes like the executable bit `+x` (_not always ideal though, as the linked issue points out_).
- I can understand wanting to avoid a compressed archive (_which should ideally [vary by platform](https://github.com/editorconfig-checker/editorconfig-checker/pull/362#issuecomment-2350459730), see [`goreleaser` config example](https://github.com/caddyserver/xcaddy/blob/master/.goreleaser.yml) as a way to support that_), running `chmod +x` afterwards resolves the executable concern anyway 👍 

---

I think a better convention is to keep the tag in the URL and leave it out of the asset name? That would allow:

```bash
# `-o` to rename to something nicer, and places at a location in `PATH` ENV
curl -fsSL -o /usr/local/bin/jaq "https://github.com/01mf02/jaq/releases/latest/download/jaq-$(uname -m)-unknown-linux-musl"
chmod +x /usr/local/bin/jaq
```

One benefit from an archive would be that the full target is separate from the binary name, so in addition to preserving `+x` I could just use:

```bash
# `-C /usr/local/bin` only needed to place the `jaq` binary there
# NOTE: The ownership from CI will be preserved as `1001:127`,
# so technically `--no-same-owner` is required for tar too (doesn't seem to be a common issue though)
curl -fsSL "https://github.com/01mf02/jaq/releases/latest/download/jaq-$(uname -m)-unknown-linux-musl.tar.gz" \
  | tar -xz -C /usr/local/bin
```

But if that adds some friction to users that aren't using CLI and would prefer the asset without the archive layer, no worries.

I just wanted to point out the benefit of omitting the version from the asset name 😎 (_which could add a [new example to the README](https://github.com/01mf02/jaq#binaries) for linux_)

**Comment by 01mf02** [comment]
I like the idea of omitting the version number, so future releases should have the shape that you proposed (see [babc05c](https://github.com/01mf02/jaq/commit/babc05cbcfacdea10b7c43a719720c8077c3bef9)).
I also like the idea of adding a new example to the README, I hope that I'll remember to put it up once 2.0 is out.

However, I'll stick without archives for now, because it's easier for users, I think.

**Comment by 01mf02** [comment]
I added download instructions in ac45dd9de86a2ecb987bb24900c78b124f70aeb1.
