### ISSUE TITLE
flatten filter yields an array in unexpected order

### ISSUE THREAD

**Issue by itchyny** [01mf02/jaq#22]
Somehow `flatten` of `jaq` yields the result in unexpected order.
```
 $ jq -nc '[[[0], 1], 2, [3, [4]]] | flatten'
[0,1,2,3,4]

 $ jaq -nc '[[[0], 1], 2, [3, [4]]] | flatten'
[2,1,3,0,4]
```

**Comment by 01mf02** [comment]
Thank you! You have discovered a bug in my implementation of `recurse`. As a result, I was even able to write a much shorter implementation.
Fixed in a1ed65cdf18fdded7b40e4b736a896b1793a4e24.
