### ISSUE TITLE
Can't use include nor import. Documentation problem? PEBCAK?

### ISSUE THREAD

**Issue by jbrains** [01mf02/jaq#225]
I'm trying to use modules/include, but I keep getting "file not found", even for the simplest case. I can only imagine that I'm doing it wrong.

I'm building `jaq` from source and it's otherwise working just fine. I've built from commit 0ef6ea33ad31a23a834d301bae72cabaf81ceacc.

```
# module.jaq
def hello: "Hello, world.";
```

```
$ ~/ThirdParty/jaq/target/release/jaq -L . 'include "module"; hello'
Error: could not load file module: file not found
  ╭─[<inline>]
  │
1 │ include "module"; hello
  ┆          ───┬──
  ┆             │
  ┆             ╰─────────── file not found
──╯
```

Whether I use `import "module" as Module` or `include "module"`, I can't get `jaq` to find the module file. It's right there in the same directory and I'm using "`-L .`". I'm running `jaq` from that directory.

What am I doing wrong? Is this an example of a misleading error message? Is this feature not supposed to work?

**Comment by wader** [comment]
Latest main seems to work for me. But i think the issue is the `.jaq`, try rename `module.jaq` to `module.jq`

**Comment by jbrains** [comment]
I tried that and it worked! And now I'm quite surprised that the file extension should be `.jq`. And I don't know where I got the idea that the extension should be `.jaq`. I guess I completely invented that! 🤷

**Comment by wader** [comment]
> I tried that and it worked! And now I'm quite surprised that the file extension should be .jq. And I don't know where I got the idea that the extension should be .jaq. I guess I completely invented that! 🤷

👍 😄 

> I suppose that, since I'm using both `jq` and `jaq`, and they behave slightly differently, it makes sense to use different file 
extensions to differentiate the files. Maybe that's wise?

I think @01mf02 aim is to make jaq more or less jq compatible so i think it make sense it uses `.jq`. The up coming 2.0 release will include quite a lot of both language and cli argument compatibility additions and fixes! 🥳

**Comment by jbrains** [comment]
> I think @01mf02 aim is to make jaq more or less jq compatible so i think it make sense it uses .jq. The up coming 2.0 release will include quite a lot of both language and cli argument compatibility additions and fixes! 🥳

I look forward to it! Even so, unless they behave _exactly_ the same (as in, a difference means a defect), then it becomes important to the user to know which files they should process with `jq` and which ones they should process with `jaq`. Forcing the extension of `.jq` on modules creates a problem that might not be obvious to a new user until they go through the same confusion I did trying to make it work.

**Comment by 01mf02** [comment]
I think that the underlying issue really is the conflation of `jq`, the implementation, and "jq", the language. jaq tries to implement the "jq" language (hence it needs to use the `.jq` extension for modules), but of course, it is not equal to `jq`, the implementation.

> Even so, unless they behave _exactly_ the same (as in, a difference means a defect), then it becomes important to the user to know which files they should process with `jq` and which ones they should process with `jaq`.

Compare the situation with C: Different compilers, such as `gcc` and `clang`, interpret the C standard differently, sometimes in quite subtle ways. Still, you can expect that most "reasonable" programs will behave the same way. My aim is similar for jaq. That's why it reads ".jq" files and not ".jaq" files, in the same way that `gcc` reads `.c` files, not `.gcc` files.
