### ISSUE TITLE
isnormal against 0 yields true but should yield false

### ISSUE THREAD

**Issue by itchyny** [01mf02/jaq#23]
The `isnormal` filter originates from the function of the same name in `math.h`, and should yield `false` against `0`.
```
 $ jq -n '0 | isnormal'
false

 $ jaq -n '0 | isnormal'
true
```
Also, the filter yields a puzzling error on non-number input.
```
 $ jq -n '"" | isnormal'
false

 $ jaq -n '"" | isnormal'
Error: cannot negate ""
```

**Comment by 01mf02** [comment]
Thanks, corrected in aad9a55.
