### ISSUE TITLE
Filenames in CLI must be UTF-8

### ISSUE THREAD

**Issue by thaliaarchi** [01mf02/jaq#231]
Filenames use `String`/`&str` throughout jaq, which restricts them to only valid UTF-8, although most file systems are less restrictive. Instead, they should be stored as `PathBuf`/`&Path`, until they need to be displayed (either with lossy UTF-8 replacements or some sort of escaping).

Something like the following should cover all the cases of how values can be provided and maintain that context for error reporting:

| Origin              | `path`   | `varname` | `kind`       |
| ------------------- | -------- | --------- | ------------ |
| Filter without `-f` | `Inline` | `None`    | `Filter`     |
| Filter with `-f`    | `File`   | `None`    | `Filter`     |
| `--arg`             | `Inline` | `Some`    | `String`     |
| `--argjson`         | `Inline` | `Some`    | `Json`       |
| `--slurpfile`       | `File`   | `Some`    | `JsonStream` |
| `--rawfile`         | `File`   | `Some`    | `String`     |

```rust
/// The source location of a filter or JSON value.
struct Loc {
    /// The path to the value.
    path: LocPath,
    /// The variable name of the argument (i.e., `--arg`, `--argjson`,
    /// `--slurpfile`, or `--rawfile`).
    varname: Option<String>,
    /// The kind of the value.
    kind: LocKind,
}

/// The path to the source of a filter or JSON value.
enum LocPath {
    /// A path to a file.
    File(PathBuf),
    /// An inline filter (i.e., filter without `-f`) or inline value to an
    /// argument (i.e., `--argjson`).
    Inline,
}

enum LocKind {
    Filter,
    String,
    Json,
    JsonStream,
}
```

I notice that your `File` type is generic over the source and path types, so it can be variably owned or borrowed. It seems all of the `String`s and `PathBuf`s should be able to be `take`n or `drain`ed from `Cli`, so no borrowing or cloning would be necessary and they can just be owned. If variably borrowing is still necessary, I think `Cow` is nicer.

**Comment by 01mf02** [comment]
Hi @thaliaarchi, thanks for this nice suggestion! I have enabled non-UTF-8 string support for all command-line arguments that may take paths in #234. Even if the code base becomes a bit more complicated, this change is also nice because it explicitly marks paths in the file loader as separate type, thus preventing confusion between paths and UTF-8 strings.

**Comment by thaliaarchi** [comment]
Looks like it was an easier fit in your existing style than I expected. Nice!
