### ISSUE TITLE
`math_rem` test fails on the i686 target

### ISSUE THREAD

**Issue by tranzystorekk** [01mf02/jaq#243]
When testing jaq 2.0.0 for Void Linux, the test run fails on the i686 platform: https://github.com/void-linux/void-packages/actions/runs/12129949574/job/33819327834?pr=50494

**Comment by tranzystorekk** [comment]
Backtrace after recompiling tests in debug:

```
---- math_rem stdout ----
thread 'math_rem' panicked at /builddir/jaq-2.0.0/jaq-core/src/lib.rs:221:9:
assertion failed: out.eq(ys)
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: jaq_core::Filter<F>::yields
             at /builddir/jaq-2.0.0/jaq-core/src/lib.rs:221:9
   4: funs::common::yields
             at ./tests/common/mod.rs:14:5
   5: funs::common::give
             at ./tests/common/mod.rs:22:5
   6: funs::math_rem
             at ./tests/funs.rs:134:5
   7: funs::math_rem::{{closure}}
             at ./tests/funs.rs:82:14
   8: core::ops::function::FnOnce::call_once
             at /builddir/rust-1.82.0/library/core/src/ops/function.rs:250:5
```

**Comment by wader** [comment]
Looks like this test https://github.com/01mf02/jaq/blob/1ac39f8bec824fc5851512f8f87e02113fc8b965/jaq-json/tests/funs.rs#L134-L138 hmm guessing 4000000001 overflows etc 32 bit system? catches error message with different number?

**Comment by tranzystorekk** [comment]
I also suspected that, but 4000000001 should fit in 32 bits just fine, and the previous tests also deal with this value without failure;

so it seems this is about the logic behind div-by-zero error catching?

**Comment by wader** [comment]
jaq seems to use `isize` so i think 4000000001 won't fitt signed 32 bit, that might be the issue. Could you try change 4000000001 to something smaller? (and also change in the error string)

**Comment by 01mf02** [comment]
@tranzystorekk, I would be happy to accept a PR from you with the smaller numbers.

**Comment by tranzystorekk** [comment]
I'm wondering if switching the int repr in jaq-json to i64 would be a viable option (I saw the comment that it allows ints to easily index arrays, but it seems the trade-off isn't as good if int is also tested against arithmetic operations)

**Comment by wader** [comment]
@GaetanLepage does a smaller number work?

**Comment by GaetanLepage** [comment]
> @GaetanLepage does a smaller number work? could try #245

Well, after more testing, I found out that the problematic line was [give(json!(null), "2.1 % 0 | isnan", json!(true));](https://github.com/01mf02/jaq/blob/b7f926801f2ad700478d9352ab12dd6ea5848eeb/jaq-json/tests/funs.rs#L118).
Commenting this one made the whole test succeed.

**Comment by wader** [comment]
Oh ok, what does `cargo run -- -n '2.1 % 0 | ., isnan, isinfinite'` say?

**Comment by GaetanLepage** [comment]
Whereas it is 
```
null
true
false
```
on `aarch64-darwin`

**Comment by wader** [comment]
Huh, is this macOS or some other darwin based os?

@01mf02 any idea what is going on? known float behaviour?

**Comment by GaetanLepage** [comment]
> Huh, is this macOS or some other darwin based os?

MacOS, running on an `aarch64` M2 CPU, but with rosetta2 emulation of `x86`.

**Comment by 01mf02** [comment]
> @01mf02 any idea what is going on? known float behaviour?

I'm sorry, I have no idea what is happening here. If it helps, the documentation for what *should* happen is here: <https://doc.rust-lang.org/std/primitive.f64.html#impl-Rem-for-f64>. Perhaps, @GaetanLepage, could you tell us what `2.1 / 0 | ., isnan, isinfinite` yields on both architectures that you tested?

**Comment by wader** [comment]
Hmm confusing, i got i M3 macbook so i guess i could install rosetta somehow. I wonder what other language implementation does, could you try this with rosetta?
```
$ node -p '2.1 % 0'
NaN
$ node -p '2.1 / 0'
Infinity
```

**Comment by GaetanLepage** [comment]
> Perhaps, @GaetanLepage, could you tell us what `2.1 / 0 | ., isnan, isinfinite` yields on both architectures that you tested?

In the meantime, our darwin builder got updated to an M4 machine.
Here are the results on this new machine:


```
$ cargo run -- -n '2.1 % 0 | ., isnan, isinfinite

# aarch64-darwin
null
true
false

# x86_64-darwin
null
false
false
```

and

```
$ cargo run -- -n '2.1 / 0 | ., isnan, isinfinite

# aarch64-darwin
null
false
false

# x86_64-darwin
null
false
true
```

**Comment by 01mf02** [comment]
@wader, this `rustc <(...)` pattern is really nice.

@GaetanLepage: Can you post the output of `rustc -o test <(echo 'fn main() { dbg!(2.1 / 0.0); }') && ./test` on your two platforms, just to make sure that the problem is on the Rust side and not on the jaq side? If they yield different outputs on your two platforms, could you perhaps file an issue on the Rust issue tracker, given that [multiplication and division should be consistent across platforms](https://github.com/rust-lang/rust/issues/75786#issuecomment-683405735)?

**Comment by GaetanLepage** [comment]
> @GaetanLepage: Can you post the output of `rustc -o test <(echo 'fn main() { dbg!(2.1 / 0.0); }') && ./test` on your two platforms, just to make sure that the problem is on the Rust side and not on the jaq side? If they yield different outputs on your two platforms, could you perhaps file an issue on the Rust issue tracker, given that [multiplication and division should be consistent across platforms](https://github.com/rust-lang/rust/issues/75786#issuecomment-683405735)?

This gives me `inf` on all `x86_64-linux`, `aarch64-linux`, `x86_64-darwin` and `aarch64-darwin`?

**Comment by wader** [comment]
Dugg a bit more

With this `float_cmp`
```rust
fn float_cmp(left: f64, right: f64) -> Ordering {
    if left == 0. && right == 0. {
        Ordering::Equal
    } else {
        let lb = left.to_bits() as i64;
        let rb = right.to_bits() as i64;
        dbg!(&left, &right);
        dbg!(lb, rb);
        f64::total_cmp(&left, &right)
    }
}
```

I get this:

```sh
$cargo run --target x86_64-apple-darwin -- -n '0.0/0.0 == 0.0%0.0'
[jaq-json/src/lib.rs:892:9] &left = NaN
[jaq-json/src/lib.rs:892:9] &right = NaN
[jaq-json/src/lib.rs:893:9] lb = -2251799813685248 # NOTE: on aarch64 this is same value as below
[jaq-json/src/lib.rs:894:9] rb = 9221120237041090560
false
```

So i wonder if one of the NaN-values gets "normalized" etc? ex the NaN payload/flags gets zeroed or something?

Still can't reproduce with same-ish code as simple rust code.

**Comment by 01mf02** [comment]
@wader, thanks for digging! Taking on your approach, may I ask you, @GaetanLepage, to post the output of the following?

    rustc -o test <(echo 'fn main() { dbg!(f64::total_cmp(&(2.1 / 0.0), &f64::INFINITY)); }') && ./test

I hope that this will yield different outputs for different architectures ... that would explain jaq's behaviour, and we could file an issue at rust-lang.

**Comment by wader** [comment]
One thought that stuck me: could compiling a simple program with rustc and building via cargo differ some way that changes float behaviour? some jaq crates dependency pokes at something? different compile optimization levels?

**Comment by GaetanLepage** [comment]
> may I ask you, @GaetanLepage, to post the output of the following?

On all architectures, I get:
```
[/dev/fd/63:1:13] f64::total_cmp(&(2.1 / 0.0), &f64::INFINITY) = Equal
```

**Comment by wader** [comment]
More digging

The two different NaNs as u64 are  these:
```
[jaq-json/src/lib.rs:890:5] lb = 18444492273895866368
[jaq-json/src/lib.rs:891:5] rb = 9221120237041090560
```
If one inspect them using my favorite website they are:
https://float.exposed/0xfff8000000000000 signed NaN
https://float.exposed/0x7ff8000000000000 "positive" NaN

I don't really follow where and how in the jaq code we end up with a signed NaN but [f64::total_cmp](https://doc.rust-lang.org/std/primitive.f64.html#method.total_cmp) will see them as no equal so maybe a solution to this and possible other NaN-differences is to do:

```rust
fn float_cmp(left: f64, right: f64) -> Ordering {
    if (left == 0. && right == 0.) || (left.is_nan() && right.is_nan()) {
        Ordering::Equal
    } else {
        f64::total_cmp(&left, &right)
    }
}
```

Are the more places to look for this? and it is ok to normalize NaN values like this? maybe only consider signness difference equal?

**Comment by 01mf02** [comment]
> One thought that struck me: could compiling a simple program with rustc and building via cargo differ some way that changes float behaviour? some jaq crates dependency pokes at something? different compile optimization levels?

I am not aware of such behaviour. On the other hand, for integers, I know that compiling with `--release` disables overflow checks.

**Comment by 01mf02** [comment]
> Are the more places to look for this? and it is ok to normalize NaN values like this? maybe only consider signness difference equal?

It may be OK to normalize NaN values like this, but first, I would like to understand what is going on here. I'd really like to reproduce the platform-specific difference without jaq-related code.

**Comment by 01mf02** [comment]
Let's get the big cannon out. Can you post the output of the following program?

~~~
fn main() {
    let t: f64 = "2".parse().unwrap();
    let z: f64 = "0".parse().unwrap();
    let vals = [t / z, z / z, t % z, z % z];
    for v in vals {
        println!("{v} (bytes = {})", v.to_bits());
    }
    for v1 in &vals {
        for v2 in &vals {
            print!("{:?}\t", v1.total_cmp(v2));
        }
        println!();
    }
}
~~~

On my computer, this yields:

~~~
inf (bytes = 9218868437227405312)
NaN (bytes = 18444492273895866368)
NaN (bytes = 18444492273895866368)
NaN (bytes = 18444492273895866368)
Equal	Greater	Greater	Greater	
Less	Equal	Equal	Equal	
Less	Equal	Equal	Equal	
Less	Equal	Equal	Equal	
~~~

**Comment by wader** [comment]
On macbook M3
```
$ rustc --target x86_64-apple-darwin  -o test test.rs && ./test
inf (bytes = 9218868437227405312)
NaN (bytes = 18444492273895866368)
NaN (bytes = 9221120237041090560)
NaN (bytes = 9221120237041090560)
Equal	Greater	Less	Less
Less	Equal	Less	Less
Greater	Greater	Equal	Equal
Greater	Greater	Equal	Equal

$ rustc --target aarch64-apple-darwin  -o test test.rs && ./test
inf (bytes = 9218868437227405312)
NaN (bytes = 9221120237041090560)
NaN (bytes = 9221120237041090560)
NaN (bytes = 9221120237041090560)
Equal	Less	Less	Less
Greater	Equal	Equal	Equal
Greater	Equal	Equal	Equal
Greater	Equal	Equal	Equal
```

(not exactly sure how x86_64 gets executed  on arm but i guess it's transparent thru rosetta, i get same result if do `arch --x86_64 ./test` which seems to the explicit way of doing it)

**Comment by 01mf02** [comment]
@wader: YES! I think we've got it. Just to be sure, can you check one last thing, namely whether replacing `t` and `z` with 2.0 and 0.0 yield the same results?

**Comment by wader** [comment]
You mean like this?
```rs
    let t: f64 = 2.0;
    let z: f64 = 0.0;
```
hmm then i get:
```
$  rust_float rustc --target x86_64-apple-darwin  -o test test.rs && ./test
inf (bytes = 9218868437227405312)
NaN (bytes = 9221120237041090560)
NaN (bytes = 9221120237041090560)
NaN (bytes = 9221120237041090560)
Equal	Less	Less	Less
Greater	Equal	Equal	Equal
Greater	Equal	Equal	Equal
Greater	Equal	Equal	Equal

$  rust_float rustc --target aarch64-apple-darwin  -o test test.rs && ./test
inf (bytes = 9218868437227405312)
NaN (bytes = 9221120237041090560)
NaN (bytes = 9221120237041090560)
NaN (bytes = 9221120237041090560)
Equal	Less	Less	Less
Greater	Equal	Equal	Equal
Greater	Equal	Equal	Equal
Greater	Equal	Equal	Equal
```

Now i'm confused. After some poking around it seems this is what differs:


```
$ rustc --target x86_64-apple-darwin -o test <(echo 'fn main() { dbg!(("0".parse::<f64>().unwrap() / "0".parse::<f64>().unwrap()).to_bits()); }') && ./test
[/dev/fd/11:1:13] ("0".parse::<f64>().unwrap() / "0".parse::<f64>().unwrap()).to_bits() = 18444492273895866368

$ rustc --target x86_64-apple-darwin -o test <(echo 'fn main() { dbg!((0.0f64 / 0.0f64).to_bits()); }') && ./test
[/dev/fd/11:1:13] (0.0f64 / 0.0f64).to_bits() = 9221120237041090560
```
but i don't see any difference in float etc:
```
$ rustc --target aarch64-apple-darwin -o test <(echo 'fn main() { dbg!("0".parse::<f64>().unwrap().to_bits()); }') && ./test
[/dev/fd/11:1:13] "0".parse::<f64>().unwrap().to_bits() = 0

$t rustc --target aarch64-apple-darwin -o test <(echo 'fn main() { dbg!(0.0f64.to_bits()); }') && ./test
[/dev/fd/11:1:13] 0.0f64.to_bits() = 0
```

Hmm is this the compiler doing some transformations etc?

**Comment by 01mf02** [comment]
@wader, great! So parsing seems to have an impact here.

I opened a bug report on rust-lang. Let's see what people have to say there.

**Comment by workingjubilee** [comment]
The aarch64 and x86-64 CPUs use different NaNs.

**Comment by workingjubilee** [comment]
This is concealed (LLVM normalizes to a particular NaN, irrespective of architecture) if you use a pattern which does not conceal the NaN. It is not if you don't.

**Comment by saethlin** [comment]
I think this was misdiagnosed/mis-minimized, and the actual bug here is that jaq is using `total_cmp`. NaN generation in Rust is effectively nondeterminstic (https://rust-lang.github.io/rfcs/3514-float-semantics.html or https://doc.rust-lang.org/stable/std/primitive.f32.html#nan-bit-patterns) and since `total_cmp` cares about which NaN is being compared, you're going to have problems like this one.

I don't know what your floating point comparison semantics are supposed to be, but I think you want all NaNs to compare less than all NaNs, or something like that.

**Comment by workingjubilee** [comment]
It seems you attempted to use `total_cmp` as a way of getting out of checking for NaN, but you should just do this:
```rust
fn float_cmp(left: f64, right: f64) -> Ordering {
    if left.is_nan() & right.is_nan() {
        Ordering::Equal
    } else {
        left == right
    }
}
```

**Comment by 01mf02** [comment]
> I don't know what your floating point comparison semantics are supposed to be, but I think you want all NaNs to compare less than all NaNs, or something like that.

This is actually what happens in jq. I have just made a PR that proposes to adopt this behaviour after all.

**Comment by 01mf02** [comment]
@workingjubilee, thanks for your suggestion, that's what I settled on in the end.
