### ISSUE TITLE
README.md typos

### ISSUE THREAD

**Issue by pkoppstein** [01mf02/jaq#31]
In `Folding (reduce .[] as $x (0, . + $x), foreach .[] as $x (0, . + $x))`

the commas should be semicolons.  

Also, it would perhaps be less confusing if the basic "thee-argument" form of `foreach` were illustrated, e.g.

    foreach .[] as $x (0; . + $x; 2 * .)

**Comment by 01mf02** [comment]
Thanks a lot, fixed in db0e6a3.
