### ISSUE TITLE
README re decimals

### ISSUE THREAD

**Issue by pkoppstein** [01mf02/jaq#41]
The jaq README currently states:

> Therefore, unlike jq, jaq satisfies the following paragraph in the [jq manual](https://stedolan.github.io/jq/manual/):

> An important point about the identity filter is that it guarantees to preserve the literal decimal representation of values. This is particularly important when dealing with numbers which can't be losslessly converted to an IEEE754 double precision representation.

Please note that the given link actually refers to the "development version" of jq. Thus, although your underlying point is fair criticism of jq 1.6 and earlier, the text quoted above really should be revised, ideally to make it clear that the "master" version of jq does indeed deal with literals losslessly, and at least to make it clear that your critique only applies to version 1.6 and earlier.
I believe that no claim was ever authoritatively made about losslessness in jq 1.6 or earlier.  

Thanks!

**Comment by 01mf02** [comment]
This is a severely confusing situation:

* The [jq 1.6 manual](https://stedolan.github.io/jq/manual/v1.6/) states that the identity filter "guarantees to preserve the literal decimal representation of values", but jq 1.6 does actually *not* preserve it.
* [This commit](https://github.com/stedolan/jq/commit/d57d9737d712ea0c72795f03013d76503635f278) claims to have removed that paragraph from the 1.6 manual, but it is still there? (Did somebody forget to regenerate the docs?)
* The [development version manual](https://stedolan.github.io/jq/manual/) does not claim anymore to preserve decimals, but actually the development version seems to preserve decimals after all, at least after a small test of mine.

Do I understand the situation correctly?

**Comment by pkoppstein** [comment]
> This is a severely confusing situation:

Yes indeed!  Currently BOTH the "development" and "1.6" versions of the manual are incorrect, so it looks like there's been a major screwup.  

(It had been my impression that there was a time when the URL for the "development" version pointed to text with the correct description of the handling of numeric literals, but now I'm not sure.)

This is what happens when a ship's first officers all take extended shore leave....

**Comment by 01mf02** [comment]
Thanks for clarifying this, @pkoppstein. I've added a paragraph to the README in 605f0c55.
