### ISSUE TITLE
README re Performance

### ISSUE THREAD

**Issue by pkoppstein** [01mf02/jaq#42]
The jaq vs jq numbers in the Performance section of the README are impressive, but I suspect that your jq numbers are based on a version of jq that has been compiled with assertion-checking turned on, and so am wondering whether you would agree that that would be worth mentioning. Also, since it's been some time (years) since the last official release of jq (v 1.6), some people might also be interested to know that the "master" version is often significantly faster.

It's easy to create a version of jq with NDEBUG in effect: basically, one has only to add -DNDEBUG to DEFS in `Makefile`.

Here are some illustrative "u+s" timings that I obtained on a 3 GHz machine for running `CMD -n empty` 128 times:
```
jaq:                    0.49s
jq-1.6                  3.96s
jqMaster                0.65s
jqMaster.NDEBUG         0.62s
```

Would you be interested in any other comparisons?

**Comment by 01mf02** [comment]
Oh, thank you for letting me know that jq master is so much faster, and that `NDEBUG` disables assertion checking!

First of all, the README.md evaluated the version installed from Ubuntu 22.04 repositories, so what `apt install jq` gives. I do not know whether this version is compiled with assertion-checking.

I compiled jq from master (cff5336) with NDEBUG, and my evaluation shows the following results:

| Command                                                                       | jaq-0.8.1 \[s\] | jq-cff5336 \[s\] | jq-1.6 \[s\] |
| ----------------------------------------------------------------------------- | --------: | ---------------: | -----------: |
| `empty` (100 iterations)                                                      |      **0.15** |             0.21 |         4.10 |
| `1000000 \| [range(.)] \| reverse`                                            |      **0.05** |             0.88 |         1.26 |
| `1000000 \| [range(.) \| -.] \| sort`                                         |      **0.15** |             0.91 |         1.38 |
| `1000000 \| [range(.) \| [.]] \| add`                                         |      **0.81** |             0.86 |         1.37 |
| `100000 \| [range(.) \| {(tostring): .}] \| add`                              |      0.23 |             **0.18** |         0.31 |
| `5000 \| [range(.) \| {(tostring): .}] \| add \| .[] += 1`                    |      0.01 |             0.01 |         2.77 |
| `100000 \| [range(.) \| {(tostring): .}] \| add \| with_entries(.value += 1)` |      **0.76** |             0.85 |         1.64 |
| `1000000 \| [limit(.; repeat("a"))] \| add \| explode \| implode`             |      **1.12** |             1.31 |         2.11 |
| `1000000 \| reduce range(.) as $x ([]; . + [$x + .[-1]])`                     |      1.27 |             **1.08** |         1.57 |
| `16 \| nth(.; 0 \| recurse([., .])) \| flatten`                               |      0.32 |             **0.22** |         0.48 |
| `16 \| nth(.; 0 \| recurse([., .])) \| (.. \| scalars) \|= .+1`               |      **0.17** |             0.58 |         1.15 |
| `100000 \| [range(.) \| tojson] \| join(",") \| "[" + . + "]" \| fromjson`    |      **0.14** |             2.85 |         3.08 |

So on eight benchmarks, jaq is fastest, on three benchmarks, jq is fastest, and on one benchmark, they are on par.

Would you include this whole benchmark on the main page? Or just the number for jaq-0.8.1 and master (cff5336)?

It is a downright shame that there is no jq-1.7 released; given that master is so much faster ...

**Comment by pkoppstein** [comment]
Your table is very useful indeed.  It would certainly be fair if you did NOT include it in the jaq README as jq 1.6 is still the latest release, and since jq ships without -DNDEBUG.  

However, if you decide NOT to include the more complex table, then I would suggest that you add some relevant comments, with perhaps a link to a page with the above table.

Ideally, we'd have a table somewhere with four data columns: jaq, jq 1.6 with assertion checking, jqMaster with assertion checking, jqMaster without assertion checking.

Thank you!

**Comment by webwurst** [comment]
I think the whole benchmark is a nice addition to the main page. Maybe even add results for [gojq](https://github.com/itchyny/gojq)?

**Comment by 01mf02** [comment]
Thank you for your comments; I have now updated the evaluation results with results from gojq and jq-cff5336.
