### ISSUE TITLE
handling of leading 0s by tonumber

### ISSUE THREAD

**Issue by pkoppstein** [01mf02/jaq#49]
```
$ jq -n ' "01" | tonumber'
1
$ gojq -n ' "01" | tonumber'
1
$ jaq -n ' "01" | tonumber'
Error: cannot parse "01" as JSON: invalid number at line 1 column 2
```

I realize the JSON specification does not permit leading 0s in numbers, but it seems to me that that is irrelevant here.

Thanks.

**Comment by 01mf02** [comment]
I am using the JSON parser from serde_json, so I cannot easily change the parser myself. Given that you write that "the JSON specification does not permit leading 0s in numbers", I also do not wish to propose such a change to serde_json.

**Comment by pkoppstein** [comment]
Has this (unfortunate) discrepancy been documented in the README?
