### ISSUE TITLE
jaq equivalent of `walk(f)`

### ISSUE THREAD

**Issue by benjamin-bergia** [01mf02/jaq#56]
Hi,

I recently discovered `jaq` and while trying to run some of my `jq` based scripts noticed that [`walk(f)`](https://stedolan.github.io/jq/manual/#walk(f)) didn't seem to be implemented. 

Is this something that is planned to be implemented at a later date or is there an alternative method/function already available to do the same thing?

**Comment by 01mf02** [comment]
Hi @benjamin-bergia, you are correct, `walk(f)` was not implemented. I just implemented it in 490147b833f5a0750242579003d329f7a94fb721. :)

**Comment by benjamin-bergia** [comment]
That's some fast support right there :D

Thanks a lot!

**Comment by 01mf02** [comment]
You're welcome! Have fun using jaq. :)
