### ISSUE TITLE
date parsing support?

### ISSUE THREAD

**Issue by MabezDev** [01mf02/jaq#58]
`jq` has `fromdate` and `fromdateiso8601` builtin functions. Is it possible to parse dates with `jaq`?

**Comment by 01mf02** [comment]
This is currently not implemented. Would you like to have a go at it? You could use the `time` crate to implement it. See https://github.com/01mf02/jaq#contributing for how to do it roughly.

**Comment by 01mf02** [comment]
There is now an implementation in #85.
