### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by pkoppstein** [01mf02/jaq#60]
congratulations on 0.10!

I noticed that there’s a superfluous line (0) in the documentation of `foreach` under the example:

```
seq 1000 | jaq -n 'foreach inputs as $x (0; . + $x)'

**Comment by 01mf02** [comment]
Thanks!

Which line do you consider superfluous? What would you have expected to see?

**Comment by pkoppstein** [comment]
My apologies - Please see updated bug report.

**Comment by 01mf02** [comment]
Thanks, corrected in 8cec36f8026d2c030697f8c8af65a399f1e245d0.
