### ISSUE TITLE
enhancement request re: %

### ISSUE THREAD

**Issue by pkoppstein** [01mf02/jaq#64]
One of the nice things about gojq is that if x and y are integers,
then `(x - (x % y)) / y` will be properly evaluated and recognized as an
integer.

Now I realize jaq has a completely different approach to numbers, but
it would be extremely convenient if jaq allowed (x % y) if x and y are
both integers in the sense that (. == floor).

At present, we find by contrast:
```
jaq -n '(7/1) % 2'
Error: cannot calculate 7.0 % 2
```

**Comment by nouritsu** [comment]
I'd love to understand this issue and implement it. Could you explain further?
From what I understand you want the modulus operator to work for floats and integers?

**Comment by 01mf02** [comment]
This is now supported as of #229. With a slight twist: When either `l` or `r` are floats, then the output of `l % r` will be a *float* as well. That is because jaq should never lose information from floats by implicit rounding.
