### ISSUE TITLE
Searching a new name for `jaq-core`

### ISSUE THREAD

**Issue by 01mf02** [01mf02/jaq#95]
You may know that in jaq, there are several sets of filters that are available by default:

- The core filters are the named filters that are implemented "natively", i.e. as Rust function (e.g. `length`).
- The std filters are the named filters that are implemented by definition (e.g. `map`).
- An unnamed filter is something like `+`, `|`, i.e. a filter with special syntax to construct it.

(The terminology *core* and *std* follows the same terminology in Rust.)

Until @passcod's introduction of native filters, core filters were implemented just like unnamed filters, both living in the `jaq-core` crate. Now, however, they are implemented apart from them, so I moved the core filters into a different package, temporarily called `jaq-native`.
This is a bit confusing, because `jaq-core` now actually does not contain the core filters, and while `jaq-native` contains *some* native filters, it is not per se about native filters (they are defined in `jaq-core`).

That's why I would like to rename `jaq-native` to `jaq-core` in order to reflect that this crate contains the core filters. But that means that I should find a new name for what is currently called `jaq-core`. Do you have a good idea for this? I was thinking about `jaq-kernel` (but that sounds a bit as if jaq was an OS, also also "kernel" and "core" are somehow the same thing). Other ideas: `jaq-base`, `jaq-filter`, `jaq-run`, `jaq-interpreter`, ...

**Comment by wader** [comment]
Not sure if it helps but jqlang/jq uses the name "builtins" for the "standard library" functions either implemented in C or in builtins.jq

**Comment by 01mf02** [comment]
Thanks. I am aware of the “builtins” terminology, but given that filters  implemented natively and filters implemented by definition occupy different libraries in jaq, I want to distinguish them by name.

I think I will go for jaq-interpret as the new name for jaq-core. That way, we could even have a jaq-compile at some point if somebody wants to explore a more jq-like architecture.

**Comment by 01mf02** [comment]
I renamed jaq-core to jaq-interpret.
